name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Hoặc nhánh bạn muốn theo dõi

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/frontend_img:${{ github.sha }} .
          docker push ${{secrets.DOCKER_USERNAME}}/frontend_img:${{ github.sha }}

      - name: SSH to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull vietanh0510/frontend_img:${{ github.sha }}
            docker stop frontend_container || true
            docker rm frontend_container || true
            docker run -d --name frontend_container -p 3000:3000 vietanh0510/frontend_img:${{ github.sha }}
